GET http://localhost:8080/products/brands-low-price
Content-Type: application/json

#res
#{
#  "statusCode": "OK",
#  "message": null,
#  "result": {
#    "productLowestPriceAndBrandResponses": [
#      {
#        "lowestBrandName": "I",
#        "lowestAllProductSumPrice": 80006
#      }
#    ]
#  }
#}
#
#Response code: 200; Time: 2009ms; Content length: 142 bytes